[system_setup]

persist_dir = "./chroma_store"
collection_name = "jenkins_logs"
ollama_url = "http://localhost:11434/api/generate"
model_name = "mistral"
no_of_commits = 10
branch = "main"
git_repo_dir = "/Users/mujaheedkhan/Desktop/development/brew"


[questions]
question1 = "What is the summary of the results so far?"
question2 = "How often did the checkout phase fail?"
question3 = "Can you tabulate how often the different phases pass or fail?"
question4 = "What seems to be the most common error?"
question5 = "How many times did the test fail?" 